### ISSUE TITLE
Inserting Mekanism tanks in controller input/output yields odd results

### ISSUE THREAD

**Issue by bmwalter68** [Edivad99/FluidSystem#2]
**Describe the bug**
When a Mekanism fluid tank is placed in the controller input/output slot the tank is returned before it is completely filled or emptied.  The amount of fluid inserted/removed is varies based on the tier of the tank inserted, 400mb for Basic, 800mb for Advanced, 1600mb for Elite and 3200mb for Ultimate

**Configuration**
Mod version: 1.3.0
Forge version: 35.1.13
Minecraft version: 1.16.4
Are you playing on server?: both SP/MP

**To Reproduce**
1. Create and valid FluidSystem tank
2. Fill a Mekanism tank with any liquid
3. Insert the tank in the controller I/O slot
4. The Mekanism tank is returned with an amount of fluid inserted/removed based on the tier of the tank

**Expected behavior**
The tank is completely emptied or filled

**Additional context**
This does not happen with Pneumaticraft tanks

**Comment by Edivad99** [comment]
It's probably a problem with Mekanism, I use the Forge API and if it works in Pneumaticraft, I don't see why it's my problem.

**Comment by bmwalter68** [comment]
This does appear to be an issue with Mekanism fluid tanks.  I've done some testing and I've not found other tank/bucket mods that have this behavior with FluidSystem and Mekanism tanks seem to have similar issues with other mods as well.  Digging through source and doing some debug work in Eclipse, I think this may have to do with Mekanism using a custom fluid handler called RateLimitFluidHandler which appears to limit transfer rates based on item tier.  Closing this adding an issue on Mekanism repo.

Thanks!
